name: iOS Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-ios-tests:
    runs-on: macos-latest  # Necessario per usare Xcode

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Clona il repository

      - name: Set Up Latest Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6"

      - name: Set Up Latest Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.4.app  # Seleziona la versione di Xcode corretta

      - name: Get Swift Version
        run: swift --version  # Verifica la versione di Swift installata

      - name: Get Xcode Version
        run: xcodebuild -version  # Debugging: mostra la versione di Xcode

      - name: List Available Simulators
        run: xcrun simctl list  # Opzionale: Mostra i simulatori disponibili

