
name: Swift Package Index Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: macos-latest 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 

      - name: Set Up Latest Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6" 

      - name: Get Swift Version
        run: swift --version  

      - name: Get Swift Tools Version
        run: swift package tools-version 

      - name: Run Tests
        run: swift test
