name: Swift Package CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-latest
    strategy:
      matrix:
        swift-version: [ "5.8.0"]
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Install Swift ${{ matrix.swift-version }}
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift-version }}

      - name: Set Up Latest Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Verify Swift Version
        run: swift --version

      - name: Verify Xcode Version
        run: xcodebuild -version

      - name: Resolve Swift Package Dependencies
        run: swift package resolve

      - name: Run iOS Tests
        run: |
          xcodebuild test \
          -scheme SwiftToast \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.4' \
          -enableCodeCoverage YES | xcpretty
